SELECT  
            GVEND.FANTASIA REPRESENTANTE,
            DECODE (GCLIENTE.CODIVI,'100','RAMON','200','TATIANE','300','CLAUDIO','2','DIRETO')ASSISTENTE,
            GCLIENTE.FANTASIA CLIENTE,
            ITE.CODI PEDIDO_MCM,
            MPALMOVR.C_ESS ESPE,
            MPALMOVR.C_LA1 LARG,
            MPALMOVR.C_COM COMP,
            NVL(ITE.QT,0) QT_PEDIDO,
            NVL(SUM(PPOP.QT),0) QTDE_PROGRAMADA,
            CAD_BITOLA.BITOLA,
            CAD_BITOLA.QUALIDADE_MP,
            CAD_BITOLA.REFERENCIAMP,
            ITE.DTENT,
            '\'|| CAD_BITOLA.REFERENCIAMP||'\' matprima1,
            NVL(ITE.QT,0) - NVL(SUM(PPOP.QT),0) SALDO,
            CASE  
                when NVL(ITE.QT,0) - NVL(SUM(PPOP.QT),0) < 0
              then 0
            else
            NVL(ITE.QT,0) - NVL(SUM(PPOP.QT),0)
            END AS AAAAAAA
    FROM ASDATA.PAPED, 
         ASDATA.PAPEDITE ITE, 
         ASDATA.GCLIENTE, 
         ASDATA.MPALMO A, 
         ASDATA.MPALMOVR, 
         ASDATA.GVEND, 
         ASDATA.PPOP,
         MCM.CAD_BITOLA
WHERE PAPED.CODI = ITE.CODI
AND ITE.DTENT < SYSDATE
AND ITE.ST IN ('A','P')
AND TO_CHAR(CAD_BITOLA.ARTIGO) = A.ALTERN
AND ITE.CODI = PPOP.PED(+)
AND ITE.SEQ = PPOP.PEDITE(+)
AND PAPED.CODIC = GCLIENTE.CODIGO
AND PAPED.CODIR = GVEND.CODIGO
AND ITE.CALMOVR = A.CODI
AND PPOP.ST(+) NOT IN ('S','D')
AND A.CODI = MPALMOVR.CODI (+)
AND  CAD_BITOLA.REFERENCIAMP = 'BOBINA DE ACO LAMINADA A FRIO SAE 1006 0,45 '
    GROUP BY 
            GVEND.FANTASIA,
            GCLIENTE.CODIVI,
            GCLIENTE.FANTASIA,
            ITE.CODI,
            MPALMOVR.C_ESS,
            MPALMOVR.C_LA1,
            MPALMOVR.C_COM,
            ITE.QT,
            CAD_BITOLA.BITOLA,
            CAD_BITOLA.QUALIDADE_MP,
            CAD_BITOLA.REFERENCIAMP,
            ITE.DTENT,
            '\'|| CAD_BITOLA.REFERENCIAMP||'\' 
    ORDER BY 1